spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fornecedor
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  application:
    name: fornecedor
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    
    properties:
      hibernate:
        show_sql: true
        format_sql: true
